version: '3.8'

services:
  inventory-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=./data/inventory.db
      - FRONTEND_URL=http://localhost:3001
    volumes:
      - inventory_data:/app/backend/data
      - inventory_uploads:/app/backend/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Development services (optional)
  inventory-dev-backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_PATH=./data/inventory.db
    volumes:
      - ./backend:/app
      - /app/node_modules
      - inventory_data:/app/data
    profiles:
      - dev

  inventory-dev-frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:3001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    profiles:
      - dev

volumes:
  inventory_data:
  inventory_uploads: